### ISSUE TITLE
Load scene and rank grasps - software tool

### ISSUE THREAD

**Issue by fbottarel** [hsp-iit/GRASPA-benchmark#1]
This is to track the development of one of the software tools we need for the benchmark. 

### Task 

The purpose of this tool is to load a Simox scene (table plane + marker + objects), parse the grasps that the user has planned for each object and test their quality and robustness according to the GWS-based metric used by GraspStudio.

### Input 
- __Simox Scene (xml):__ collection of xml objects. Every object has its own mesh for display and collision detection purposes. The pose of each object is specified by a 4x4 matrix, and the origin of the ref frame is placed in the center of the aruco marker. Objects and scenes are stored in the [data](https://github.com/fbottarel/RAL-benchmark-code/tree/master/data) directory
- __Grasp Sets (xml):__ xml objects containing grasps planned by the user. __For the time being__, I am considering an xml file for each object in the dataset. In Simox terms, these are ManipulationObjects that contain information about 
   - the object, its xml file and related meshes
   - the scene each object appears in. For each object, Simox allows the storage of different Grasp Sets. We will consider a different GraspSet for every single scene each object appears in
   - single grasps. For each grasp, we can specify a different robot+endeffector+pregrasp combo. By default, the program will evaluate every grasp with its respective configuration, but the user can choose to ignore some via command line parameters. Each grasp will have its own pose, expressed as a 4x4 matrix __in the global ref frame (the marker)__. This is different from what Simox considers by default (ref frame as the center of the object). 

### Output 

Not sure yet about how to formalize the output. It will, however, express the quality of each grasp planned for the scene (or an average, if multiple grasps are planned for the same object) and some information about their robustness. 

This information needs to be readable by some other tool in the benchmark chain.

### TODO List

- [x] Understand GraspStudio manipulation data types (what they contain, how they are loaded and stored)
- [x] Ground example: automatically load some object and poses (generated by Simox's own tools) and rank them
- [x] Study the literature and find information about the metric Simox is using for grasp quality
- [x] Produce a base example that can load a scene and all the user-defined grasps for such scene, display their information and test them
- [ ] Implement `closeActors` method for end effector closure with joint trajectories 
- [ ] Implement contact check if the user is providing contact location with their grasps
- [x] Use Simox's 3D visualization tools in order to view the scene and the robot endeffector executing grasps
